name: Photo gallery
markdown: redcarpet
pygments: true
permalink: /:year/:month/:title/
url: https://nadjetey.github.io/GridGallery/
author:
    name: Giorgio Baldelli
    twitter: #

baseurl: '/gallery'
url: "http://giorgiobaldelli.com" # the base hostname & protocol for your site
