name: Photo gallery
markdown: redcarpet
pygments: true
permalink: /:year/:month/:title/
author:
    name: Giorgio Baldelli
    twitter: #

url: "http://giorgiobaldelli.com/gallery" # the base hostname & protocol for your site
